name: ts2024
channels:
  - conda-forge
dependencies:
  - python=3
#jupyter
  - jupyterlab
  - jupyter-server-proxy
  - jupyter_core
  - jupyter_server
  - widgetsnbextension
  - dask-labextension
  - nodejs
  - notebook
  - nbclassic
  - nbclient
  - ipywidgets
    #- notebook=6.4.0
    #- nbclassic=0.3.1
    #- nbclient=0.5.3
#xarray-related
  - rioxarray
  - zarr
# db related
  - sqlalchemy
  - psycopg2
#other 
  - fsspec
  - s3fs
  - erddapy
  - xmltodict
  - folium
#aws
  - boto3
  - awscli
#ODC
  #- datacube
  #- odc-stac
# gaass-py
  - pandas
  - numpy
  - rasterio
  - matplotlib
  - geopandas
  - shapely
  - scikit-learn
  - scikit-image
  - pipe
  - tqdm
  - geojson
# plotting
  - plotly
  - holoviews
  - geoviews
  - hvplot
  - datashader
  - panel
  - seaborn
  - cartopy
# stac VERSIONS are Important Here - bummer!
  - rioxarray
  - pystac
  - pystac-client
    # - pystac=1.1.0
    # - pystac-client=0.3.0
# CPU
  - psutil
  - scalene
  - yaml
  - python-ldap
    #- pyan3=1.1.1
# PIP Things
  - pip
  - pip:
    - tabulate
    - pyan3==1.1.1
    - loguru
    - python-dotenv


